### ISSUE TITLE
Generate/add occupancy grid maps for all the world description files

### ISSUE THREAD

**Issue by Sushant-Chavan** [DharminB/ropod_sim#1]
Currently the world descriptions are only modeled using xacro. It would be useful to have occupancy grid maps generated for these maps as it is required for robot navigation.

**Comment by Sushant-Chavan** [comment]
@DharminB I need at least one occupancy grid map for completing the multi-robot simulations. 

The occupancy grid map for BRSU is available in [Gitlab](https://git.ropod.org/ropod/wm/occupancy_grids/tree/develop/brsu/brsu-c-floor0_osm), but it differs slightly from the xacro model file. For example, at the university entrance.

**Comment by DharminB** [comment]
Could you copy it from here locally for now please. I will commit it ASAP (probably today)

**Comment by Sushant-Chavan** [comment]
> Could you copy it from here locally for now please. I will commit it ASAP (probably today)

I can wait until you commit it. :)

I have done my testing assuming the occupancy grid maps will be available at the path `world_description/occupancy_grids/`. For example, for the BRSU map, I assume that the files `world_description/occupancy_grids/brsu.pgm` and `world_description/occupancy_grids/brsu.yaml` are available.

**Comment by DharminB** [comment]
> > Could you copy it from here locally for now please. I will commit it ASAP (probably today)
> 
> I can wait until you commit it. :)
> 
> I have done my testing assuming the occupancy grid maps will be available at the path `world_description/occupancy_grids/`. For example, for the BRSU map, I assume that the files `world_description/occupancy_grids/brsu.pgm` and `world_description/occupancy_grids/brsu.yaml` are available.

Done https://github.com/DharminB/ropod_sim/commit/7f59d90f8897d1d126c809328e4a2cd1f37fd6d7. Let me know if that is sufficient. I have not added occ grid for hall.xacro but I don't think that'll be used for any meaningful application. If that is sufficient, I can close this issue.

**Comment by Sushant-Chavan** [comment]
Thanks, that works for me. You can close the issue :)
